services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  pythonserver:
    image: python:3.12-slim
    container_name: pythonserver
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      sh -c "pip install flask && python -m http.server 8080"

volumes:
  grafana_data:

